# Really important things
GAME_NAME = "Infinite Platforms"

# Frames per second
FPS = 60


# Colours
BLACK = "#000000"
DARK = "#43523d"
LIGHT = "#c7f0d8"
RED = "#ff0000"
NEON_BLUE = (21, 132, 247)
NEON_PINK = (245, 39, 137)

# Actor dimensions
TILE_SIZE = 64
PLAYER_WIDTH = TILE_SIZE // 2
PLAYER_HEIGHT = TILE_SIZE
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)

# Window dimensions
WINDOW_WIDTH_IN_TILES = 10
WINDOW_WIDTH = WINDOW_WIDTH_IN_TILES * TILE_SIZE
WINDOW_HEIGHT_IN_TILES = 8
WINDOW_HEIGHT = WINDOW_HEIGHT_IN_TILES * TILE_SIZE
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
WINDOW_HORIZONTAL_CENTER = WINDOW_WIDTH // 2
WINDOW_VERITICAL_CENTER = WINDOW_HEIGHT // 2
WINDOW_CENTER = (WINDOW_HORIZONTAL_CENTER, WINDOW_VERITICAL_CENTER)

# Sounds
MUTE = True

# Physics
NUM_OF_PLATFORMS_BEFORE_SPEED_INCREASE = 4
MAX_PLATFORM_SPEED = 4.5
EXIT_AMOUNT = 20
